name: fnotes
description: Note taking application

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  bloc_test: ^8.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0
  fnotes_ui: 
    path: packages/fnotes_ui
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  queen_validators: ^0.2.3

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.2
  lint: ^1.5.3

flutter:
  uses-material-design: true